### ISSUE TITLE
Creators cannot delete quizzes

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#94] opened 2015-01-12 16:51 UTC

**Comment by simpsonw** [comment] 2015-01-20 17:35
I'm unable to reproduce this issue.  The delete button is appearing when I'm logged in as a creator and I am able to delete the quiz without issue.  Are there any more steps I need to take to reproduce it?

**Comment by simpsonw** [comment] 2015-01-20 17:43
This is working on the master branch and I've confirmed that it works on the UAL production server.  Closing as a possible duplicate of #20.

**Closed by simpsonw** 2015-01-20 17:43 UTC
Labels: bug
