### ISSUE TITLE
Magnify images

### ISSUE THREAD

**Issue by yvonnemery** [ualibraries/Guide-on-the-Side#75] opened 2014-05-21 16:00 UTC
Would like to see the ability for users to magnify an image.

**Comment by simpsonw** [comment] 2015-01-20 20:40
I've looked into this a bit and it seems possible but there is an important caveat: it appears that the images have been getting resized upon upload, so the magnify feature would not work retroactively.

**Comment by simpsonw** [comment] 2015-01-23 00:15
I have the functionality working on the PHP side to create a thumbnail/original image pair, but I'm having some issues getting the JavaScript to output the thumbnail in such a way that it can be linked to the original.

**Comment by simpsonw** [comment] 2015-01-23 21:49
I was working some more on this and noticed that images in the thumbnail folder I created weren't showing up when I previewed the tutorial despite being there while I was editing it.  I was curious as to what had broken this, so I reverted to a previous revision.  To my surprise, it appeared as though any time an image wasn't in uploads/images, it wouldn't be properly output.  I checked and it looked like the src attributes were being rewritten somehow for images in that folder.

I couldn't figure out what was going on until I found the SteppableBehavior class.  The function _parseImages appears to rewrite the src attributes of images who are in the uploads/images folder using regular expressions.

Parsing HTML with regular expressions is generally a bad idea as is hardcoding a particular directory that images have to be in, doubly so when the directory in question is set in a configuration file next to a comment telling you to change the path to suit your needs.

It's probably outside the scope of this task to rewrite that functionality, but I think I may create another task.  At the very least, this should be documented, although it would be preferable to outright fix it.

**Comment by michaelhagedon** [comment] 2015-01-23 22:08
> Parsing HTML with regular expressions is generally a bad idea...

Agreed! I've never been very comfortable with GotS' reliance on regular expressions (it's not just _parseImages; it's all of SteppableBehavior). I should have used a proper parser.

> ... as is hardcoding a particular directory that images have to be in, doubly so when the directory in question is set in a configuration file next to a comment telling you to change the path to suit your needs.

I assume you're talking about the TinyMCE phpimage plugin config.php. That was borrowed code, and I assumed GotS users wouldn't find that. But you're right -- it's weird!

> It's probably outside the scope of this task to rewrite that functionality, but I think I may create another task. 

Please do. :-) I would love this to be better.

**Comment by simpsonw** [comment] 2015-01-23 22:45
Thanks for the feedback!  I kind of figured that there were two separate tasks in there: one to rewrite the SteppableBehavior using an XML/HTML parser and another to make the upload location for imags more flexible, so I've created #105 and #104 to address these issues.

**Comment by simpsonw** [comment] 2015-01-26 23:54
I have the basic functionality for this working.  Here's the basic workflow:

* User uploads a picture via TinyMCE
* Two copies are saved to the server, one in the original resolution and the other resized.
* The TinyMCE editor outputs a link with an href property pointing to the original resolution image that wraps an img tag that has a src attribute pointing to the resized image.
* When the user clicks on the image in a tutorial, a jQuery UI dialog box pops up containing the image in the original resolution.

There are definitely some kinks to work out regarding responsiveness and cross browser compatibility, but the basic idea is there.

**Comment by simpsonw** [comment] 2015-01-27 18:50
I think this is pretty much ready to go.  I have tested it on the following platforms:

* Firefox 35 for Linux Mint
* Google Chrome 40 for Linux (64 bit)
* Internet Explorer 11 on Windows 8
* Internet Explorer 10 on Windows 7
* Internet Explorer 9 on Windows 7
* Internet Explorer 8 on Windows XP

I don't have a Mac handy, so I have not tested Safari, so that would be a good thing for whoever  wants to review this.  My changes are in the (unfortunately misnamed)  gh_76_magnify_images branch.

**Comment by yvonnemery** [comment] 2015-01-27 18:53
The images are much clearer now, so I think this is fixed.
Thanks

**Comment by simpsonw** [comment] 2015-01-27 19:41
@yvonnemery, I just deployed what I have to 

http://webdev.library.arizona.edu/applications/quickHelp/tutorial/1-image-magnify-demo

There are three chapters, each with an image.  Click on the image to see the full resolution image.  Let me know what you think of the functionality and behavior.

**Comment by yvonnemery** [comment] 2015-01-27 19:43
It works great!

**Comment by michaelhagedon** [comment] 2015-01-27 20:03
Nice, @wsimpson! I like it. 

The first image in that example takes over the whole screen on my computer, and I wonder if people will lose the fact that they're still in a tutorial. Maybe a max size on the dialog would be good?

**Comment by simpsonw** [comment] 2015-01-27 20:17
Sounds like a good idea, @michaelhagedon, I will give that a shot.

**Comment by simpsonw** [comment] 2015-01-28 21:09
I have deployed a few changes to webdev:

* The height and width are capped so they don't take up so much of the screen (see the first and last image on http://webdev.library.arizona.edu/applications/quickHelp/tutorial/1-image-magnify-demo/single-page)
* A bug that was causing the modal images to be broken in single page mode has been fixed.

Let me know what you think @michaelhagedon and @yvonnemery (and anyone else!).

**Comment by yvonnemery** [comment] 2015-01-28 21:13
Not sure I am giving you the correct feedback here, but the when I click on Image 1 it opens so that I only see about ½ of the picture.
Yvonne

**Comment by simpsonw** [comment] 2015-01-28 21:30
Interesting.  Could you tell me which browser and operating system you're using, @yvonnemery?

**Comment by yvonnemery** [comment] 2015-01-28 21:31
Firefox. Windows.
You can come look. At my desk and that is rare.

**Comment by simpsonw** [comment] 2015-01-28 21:47
Looks like @yvonnemery was being served a cached copy of the page.  After the cache was cleared, everything displayed properly.

**Comment by simpsonw** [comment] 2015-01-29 16:43
This has been moved into review.  If @michaelhagedon or anyone else wants to review this so I can merge it, I would really appreciate it.

**Comment by michaelhagedon** [comment] 2015-02-03 20:07
Sorry for the delay... I checked out this branch and when I upload an image the thumbnail doesn't show up. This is in the logs:
```
2015-02-03 13:03:22 Error: [MissingControllerException] Controller class UploadsController could not be found.
Exception Attributes: array (
  'class' => 'UploadsController',
  'plugin' => NULL,
)
Request URL: /guide_on_the_side/uploads/thumbnails/vast_auth.png
Stack Trace:
#0 /var/www/guide_on_the_side/app/webroot/index.php(107): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
```

When I click on the broken thumbnail, I do see the full image. Which brings me to something we maybe didn't consider: how does this feature interact with popup mode? The image might actually get smaller in the lightbox...

**Comment by simpsonw** [comment] 2015-02-03 20:20
@michaelhagedon I haven't run into that issue with uploading images.  Out of curiosity, what are the permissions on your app/webroot/uploads folder?  And which version of CakePHP are you running?

Regarding popup mode, right now it's trying to make an educated guess as to how tall the viewport is and trying to take up as much of it as possible, e.g.

![gots_popup_eiffel_tower](https://cloud.githubusercontent.com/assets/10437788/6028489/389b9fee-aba7-11e4-93dd-7f2c65952d38.png)

![gots_screenshot_eiffel_tower_2](https://cloud.githubusercontent.com/assets/10437788/6028494/3d1653c0-aba7-11e4-8198-deb625707b81.png)

There does seem to be an issue with landscape images, however:
![brandenburger_tor](https://cloud.githubusercontent.com/assets/10437788/6028512/62fb7cc8-aba7-11e4-807c-9bdb916e831a.png)

Not sure what the best way to go here would be, I'll have to mull it over.

**Comment by michaelhagedon** [comment] 2015-02-03 20:25
> Out of curiosity, what are the permissions on your app/webroot/uploads folder?

777

> And which version of CakePHP are you running?

2.4.2... maybe should upgrade.

> There does seem to be an issue with landscape images, however

Ah, the portrait ones look good. I was using a landscape image.

**Comment by simpsonw** [comment] 2015-02-03 20:27
Hmm, I'm running 2.4.10, so I don't know if that's related.  I will try downloading 2.4.2 and see if that allows me to reproduce the problem.

**Comment by simpsonw** [comment] 2015-02-03 20:39
I tried replacing my lib folder with Cake 2.4.2 and I didn't experience the issue.  Maybe try changing debug in core.php to 2 to help clear out any caching?  Or possibly delete the contents of the tmp folder?

**Comment by simpsonw** [comment] 2015-02-04 17:57
I've added a different behavior for popup mode.  Instead of using a modal dialog, images are opened in a new window.  See the example below:
![popup_mode](https://cloud.githubusercontent.com/assets/10437788/6046109/7e0a75c2-ac5c-11e4-8cdc-c5575c2b629a.png)

**Comment by simpsonw** [comment] 2015-02-04 21:04
I was doing some testing and noticed an issue with IE8.  Apparently, IE8 won't allow you to have spaces in the title parameter of a window.open() call.  Previously, I had been creating an HTML document containing the image in JavaScript so that the window could use the supplied title for the image.  However, if you have a space (e.g. "Eiffel Tower"), the window won't open in IE 8, so I simplified things and made it directly open the image file in the popup.

**Comment by simpsonw** [comment] 2015-02-04 21:10
I would say this is ready for review again, but I'm not sure what to do regarding the build issues that @michaelhagedon is having.

**Comment by michaelhagedon** [comment] 2015-02-06 23:36
I upgraded to Cake 2.4.10 and that didn't help. So I re-cloned and re-installed GotS from this branch and now it works as expected (still with Cake 2.4.10). So let's say there was just something wrong with my installation. 

It looks good! One question -- is it possible / wise in popup mode to make the image popups adjust more to the size of the image?

**Comment by simpsonw** [comment] 2015-02-07 00:11
@michaelhagedon I think it may be possible to make the popup mode windows adjust more to the size of the image.  Maybe a strategy along the lines of "preserve the aspect ratio with a maximum dimension of x pixels" would make sense.

**Comment by simpsonw** [comment] 2015-02-11 18:58
@michaelhagedon I've changed the code a bit so that it tries to match the size of the popup window to the aspect ratio of the image it's displaying.  I have tested in the following browsers:

* Firefox 35 on Linux
* Firefox 32 on Windows 8
* Chrome 40.0.2214.111 (64-bit) on Linux
* IE 11 on Windows 8
* IE 10 on Windows 7
* IE9 on Windows 7
* IE8 on Widows XP

Let me know what you think!

**Comment by liquid06** [comment] 2015-02-13 00:34
I ended up rebuilding my local copy because I encountered this when editing a tutorial after checking out this branch:

![gots-popupmode](https://cloud.githubusercontent.com/assets/460005/6179724/34f30cfe-b2d9-11e4-88b6-a663a0a39211.png)

Weird.

Anyway, I tried uploading a few different kinds of images. Sometimes in a tutorial, the creator will add an image of a small part of the interface, like a button or a drop-down, so the person can visually match what they're supposed to be looking for between the tutorial and the actual site.So I added a tiny image that was 145px wide. 

![request-this-item](https://cloud.githubusercontent.com/assets/460005/6179959/e05a08ac-b2db-11e4-923c-28c6efaec6cd.png)

The appearance settings seem to be automatically set to 300px wide. This is likely a totally different problem, and mainly a usability problem, but it added a 300 width attribute to my tiny image and made it look weird on the tutorial. Do tutorial creators currently have to manually type in the dimensions for every image they add? That should be a bug IMO.

![request-this-wide](https://cloud.githubusercontent.com/assets/460005/6179974/0b39689c-b2dc-11e4-9171-26b469ea3e27.png)

More relevant to magnify images, my image looked correct (145px) when I magnified it, but in popup mode the window it shows up in is soooo much bigger. It was the full width of my screen and half the height! It was reasonably sized in side-by-side and single-page mode.

Also likely a different issue, but this is the first time I'm looking in much detail at the process for uploading images...I'm assuming this means my file is too big?

![cant-carry-on](https://cloud.githubusercontent.com/assets/460005/6179903/405818b2-b2db-11e4-9eba-28cd4a974234.png)

Other details I noticed about the front-end:
* It feels a little awkward to have underlines on the image links because they already have kind of a border effect. Maybe they don't need underlines or maybe they need some different indication that they're links (and maybe they don't need borders, but I think we had captions in mind when those were added and I think those are still a feature request)
* The right margin is off and it's even more obvious with the images because they're nearly touching the scrollbar. I'm not sure when that happened, and maybe it should be a different ticket, but it's really bugging me. I don't see it in your screenshots, Will, but I'm seeing it in my local copy (tested in IE edge and chrome)

![right-margin](https://cloud.githubusercontent.com/assets/460005/6180021/c3fbf110-b2dc-11e4-8754-ff4e06f2f37c.png)

**Comment by liquid06** [comment] 2015-02-13 17:20
I looked through the commits related to this issue for review against our best practices. #111 looks like it covers indentation, so I looked at style details from a "when in Rome" perspective of what's in other parts of the file. Mostly you're missing spaces before brackets and parens when the rest of the file includes them, and that's all I found for possible review corrections.

* In d5b5b516f53a7433a72420635ebf2cd49a0fe242 in image.php.
* In 86d903214ef301b5b692d2ff4d14a8cf3f27ab8e in image.js, line 21.
* In f00cc9235649c367255dcd938c17135989276a67 the changes in tutorial_content.ctp.

I filed #116 for work on best practices changes for the CSS.

**Comment by simpsonw** [comment] 2015-02-16 19:09
@liquid06 Thanks for the awesome feedback!

>The appearance settings seem to be automatically set to 300px wide. This is likely a totally different problem, and mainly a usability problem, but it added a 300 width attribute to my tiny image and made it look weird on the tutorial. Do tutorial creators currently have to manually type in the dimensions for every image they add? That should be a bug IMO. edit: Maybe that's actually issue #74

You are correct.  Right now the images are being resized regardless of whether or not they are smaller than the supplied resize dimensions.  I definitely agree that we should fix that and I believe that's what they are referring to in #74, so I think we should take care of it there.

>More relevant to magnify images, my image looked correct (145px) when I magnified it, but in popup mode the window it shows up in is soooo much bigger. It was the full width of my screen and half the height! It was reasonably sized in side-by-side and single-page mode.

Wow, I'm really glad you caught that!  I have committed some new code (3aa4f61) to address that.  It seems to be working for me, but please test it and let me know.

>Also likely a different issue, but this is the first time I'm looking in much detail at the process for uploading images...I'm assuming this means my file is too big?

That is correct.  I found that message to be rather confusing, but I have not changed it since it lives in class.upload.php, which I gather is third party code, so I'm not sure under which other circumstances (if any) that message would display.


>It feels a little awkward to have underlines on the image links because they already have kind of a border effect. Maybe they don't need underlines or maybe they need some different indication that they're links (and maybe they don't need borders, but I think we had captions in mind when those were added and I think those are still a feature request)

Agreed.  I think getting rid of the bottom border and possibly adding a hover effect might be a better way to show that they're links.

>The right margin is off and it's even more obvious with the images because they're nearly touching the scrollbar. I'm not sure when that happened, and maybe it should be a different ticket, but it's really bugging me. I don't see it in your screenshots, Will, but I'm seeing it in my local copy (tested in IE edge and chrome)

This is also happening for me on Chrome and IE, but not FF.  I will see if I can isolate the cause.

**Comment by simpsonw** [comment] 2015-02-16 21:39
I've added some new styling for the popup/modal images.  I've gotten right of the underline/bottom border and added a blue border/shadow that shows up when you hover over an image that links to a modal dialog or popup:

![gh_75_hover_border](https://cloud.githubusercontent.com/assets/10437788/6219636/94b8425e-b5e9-11e4-9b6d-957106cbbeb0.png)

How does that look to you guys?

**Comment by simpsonw** [comment] 2015-02-16 22:03
@liquid06 Regarding the right margin issue, I appear to be having the same problem, it's just that the Eiffel tower picture that's in most of my screenshots happens to be skinny enough to make it not so apparent:

![gh_75_right_margin](https://cloud.githubusercontent.com/assets/10437788/6219840/f228f120-b5eb-11e4-9f2f-20464daf227d.png)

This appears to be a rather old issue; I checked out 1.0-beta3 and still saw it, so I have created issue #117 to cover that.

**Comment by simpsonw** [comment] 2015-02-16 22:21
@liquid06 I have looked into cleaning up the non-CSS code format issues in commit a9cdcbf

**Comment by liquid06** [comment] 2015-02-18 23:51
@simpsonw: I think everything has been addressed and split out into separate tickets that make more sense. Thank you! I had some trouble with my local build, but was finally able to test the style change for the images by interacting with them - I think that's a big improvement! IMO it's ready to go. As we're testing the upgrade process, we should remember to write up how this affects content creators; if they want this feature for already-existing tutorials, they'll need to re-upload the images.

**Closed** 2015-02-19 18:47 UTC
Labels: enhancement
