### ISSUE TITLE
Issue with creating a Question

### ISSUE THREAD

**Issue by sephyrix** [ualibraries/Guide-on-the-Side#86] opened 2014-08-27 23:52 UTC
Hi I'm from CSUSM and I've been having some trouble with adding a question for quizzes. After entering in all the information for the quiz, it seems to just display the number of times I have attempted to create a quiz. Any help would be appreciated.

![questioncreation](https://cloud.githubusercontent.com/assets/6351506/4069353/1f0f5f1e-2e45-11e4-86ae-7e4552d05372.PNG)

**Comment by michaelhagedon** [comment] 2015-01-12 16:49
We've seen this issue a number of times, and it may be fixed in master, but it needs more testing.

**Comment by simpsonw** [comment] 2015-01-28 22:30
I was unable to reproduce this issue locally.  I checked out of the 1.0-beta3 release and set up a database and tried adding and editing a quiz and its questions, but never got the error.  Do we have any more information about the steps needed to reproduce the issue?

**Comment by simpsonw** [comment] 2015-02-06 17:49
I'm still stumped by this one.  Upon closer inspection, it appears that the screenshot is not from 1.0-beta3 since there's a delete button for the quiz, which didn't show up until after that release.  I tried looking at the commit history for the associated templates and JavaScript files, but I didn't see anything that looked like it would be related to this.  I also tried checking out a few individual commits that seemed to be from around the same time (e.g. 86af528ae94e697aa1d786ada7f17fa38bd083f9), but I was still unable to reproduce the problem.

I also noticed that the screenshot seems to be using a custom theme, so I don't know if it's possible that it was an issue with that theme rather than GotS core.  Has this bug ever popped up for anyone using a different theme, particularly the default Guide On The Side theme?

**Comment by michaelhagedon** [comment] 2015-02-12 06:20
I believe I've seen this before, so I don't think it's their theme.

**Comment by simpsonw** [comment] 2015-02-18 17:56
I've been able to shed a little light on this; if an error occurs inside of the add_edit_form_submit function in app/webroot/js/questions/add.js, you will get the behavior specified in this issue:

![question_add_error](https://cloud.githubusercontent.com/assets/10437788/6253135/7d99397e-b75c-11e4-9ec4-920e963087ef.png)

I was able to get this to happen by deliberately adding garbage characters into the add_edit_form submit, so at least that narrows things down a little.  The question is, of course, what could cause this to happen "in the wild".

**Comment by simpsonw** [comment] 2015-02-18 21:44
I have been unable to reproduce this problem without deliberately messing up the JavaScript.  I don't have much information to go on with this issue, so I think I will have to close this task for the time being.

If anyone encounters this problem in the future, please note the circumstances under which it happened and check your JavaScript console for errors.

**Closed by simpsonw** 2015-02-18 21:44 UTC
Labels: bug
